.Dd Jun 26, 2018
.Dt ZATCH 1
.Os
.Sh NAME
.Nm zatch
.Nd efficiently watch directory changes on macOS
.Sh SYNOPSIS
.Nm
.Op Fl hps
.Ar dir ...
.Sh DESCRIPTION
.Nm
efficiently watches directory changes on macOS. It does this by coalescing all changes in a directory that happen within 30 ms and echo a line on stdout to indicate that one or more things changed in that directory or any of it's subdirectories.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
Print usage and exit.
.It Fl p
Preflight - echo the name of each dir on the command line once before starting to monitor.
.It Fl s
Show subdirs to narrow down where a change occurred. Note that this ensures a trailing "/" after the echoed dir. Furthermore, since all changes within 30 ms are coalesced, some changes might have occurred in a subdirectory of the one that is echoed.
.It Fl V
Print version and exit.
.It Ar dir
One or more directories to watch.
.El
.Pp
.Sh EXIT STATUS
.Ex -std 
.Sh AUTHORS
.An -nosplit
.An Tim Kuijsten Aq Mt tim@netsend.nl
